using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

/// <summary>
/// This class is used to handled exceptions that are generated by the application and used to 
/// display friendly error messages to the client, 
/// for example business logic or validation exceptions 
/// caused by incorrect input from the user
/// </summary>
namespace SMS.API.WEB.Helpers
{
    public class AppException : Exception
    {
        public AppException():base()
        {
        }
        public AppException(string message):base(message)
        {
        }
        public AppException(string message,params object[] args):base(string.Format(CultureInfo.CurrentCulture,message,args))
        {
        }
    }
}
