//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Employees = new HashSet<Employee>();
            this.EnrolledStudents = new HashSet<EnrolledStudent>();
        }
    
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string PlaceOfBirth { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberVerified { get; set; }
        public string Email { get; set; }
        public bool EmailVerified { get; set; }
        public string UserName { get; set; }
        public string NameSpace { get; set; }
        public byte[] Password { get; set; }
        public Nullable<System.DateTime> PwdChangeDate { get; set; }
        public Nullable<bool> PwdChangeRequired { get; set; }
        public bool IsEnabled { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public bool IsLocked { get; set; }
        public Nullable<System.DateTime> LockedTime { get; set; }
        public Nullable<int> FailedLoginCount { get; set; }
        public byte[] Salt { get; set; }
        public bool IsActive { get; set; }
        public string PublicId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrolledStudent> EnrolledStudents { get; set; }
        public virtual NamespaceType NamespaceType { get; set; }
    }
}
