//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AttendanceView
    {
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string PhoneNumber { get; set; }
        public int AttendanceId { get; set; }
        public bool Present { get; set; }
        public bool Permission { get; set; }
        public bool Late { get; set; }
        public int ScheduleId { get; set; }
        public int ScheduleDetailId { get; set; }
        public System.DateTime Date { get; set; }
        public int ClassId { get; set; }
        public int BranchId { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> SectionId { get; set; }
        public string SectionName { get; set; }
        public int EnrolledStudentId { get; set; }
        public int SubjectId { get; set; }
        public string SubjectName { get; set; }
    }
}
