//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RegisteredBranchPerCalendarYear
    {
        public int CalendarYearId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool IsCalendarYearActive { get; set; }
        public int BatchId { get; set; }
        public bool IsBatchActive { get; set; }
        public int BranchId { get; set; }
        public string BranchName { get; set; }
        public bool IsBranchActive { get; set; }
        public bool IsMainBranch { get; set; }
        public int SchoolID { get; set; }
        public string SchoolName { get; set; }
        public bool IsSchoolActive { get; set; }
    }
}
